name: Build APK

on:
  push:
    branches:
      - master # Trigger the workflow on push to the master branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: "11" # Use the Java version compatible with your project
          distribution: "temurin"

      - name: Install SDK
        run: |
          sudo apt-get update
          sudo apt-get install -y android-sdk
          echo "sdk.dir=/usr/lib/android-sdk" > local.properties

      - name: Install Specific Gradle Version
        run: |
          wget https://services.gradle.org/distributions/gradle-8.0-bin.zip
          unzip gradle-8.0-bin.zip
          sudo mv gradle-8.0 /opt/gradle
          sudo ln -s /opt/gradle/bin/gradle /usr/bin/gradle  # Create a symlink for the gradle command

      - name: Build APK
        run: gradle assembleRelease

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: apk
          path: app/build/outputs/apk/release/app-release.apk
