name: Build Android APK

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Java JDK
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin' # Or another distribution like 'zulu'

    - name: Install required packages
      run: |
        sudo apt-get update
        sudo apt-get install -y unzip wget

    - name: Download Android SDK Command-Line Tools
      run: |
        wget https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip -O commandlinetools.zip

    - name: Extract Android SDK Command-Line Tools
      run: |
        mkdir -p $HOME/android-sdk/cmdline-tools
        unzip commandlinetools.zip -d $HOME/android-sdk/cmdline-tools
        rm commandlinetools.zip

    - name: Set up Android SDK environment
      run: |
        echo "export ANDROID_HOME=$HOME/android-sdk" >> $GITHUB_ENV
        echo "export PATH=$PATH:$HOME/android-sdk/cmdline-tools/bin" >> $GITHUB_ENV

    - name: Accept licenses and install SDK packages
      run: |
        sdkmanager --sdk_root=$HOME/android-sdk --licenses
        sdkmanager --sdk_root=$HOME/android-sdk "platforms;android-30" "build-tools;30.0.3"

    - name: Build APK
      run: |
        ./gradlew assembleRelease
