name: Build APK

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '11'  # Adjust as needed for your project

    - name: Build APK with Docker
      uses: docker://openjdk:11-jdk
      with:
        entrypoint: /bin/bash
        args: -c |
          apt-get update && apt-get install -y wget unzip
          wget https://services.gradle.org/distributions/gradle-7.5-bin.zip
          unzip gradle-7.5-bin.zip
          export GRADLE_HOME=$PWD/gradle-7.5
          export PATH=$PATH:$GRADLE_HOME/bin
          ./gradlew assembleRelease  # or ./gradlew assembleDebug depending on your needs

    - name: Archive APK
      uses: actions/upload-artifact@v3
      with:
        name: apk
        path: app/build/outputs/apk/release/app-release.apk  # Adjust the path if necessary
