name: Build APK

on:
  push:
    branches:
      - master  # Adjust to your branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'  # Use 'temurin' instead of 'adopt-openjdk'

    - name: Build APK
      run: |
        cd app/src/main
        javac -d out $(find . -name '*.java')
        jar cvf app-release.jar -C out .
        # Replace with actual APK build commands if needed
