name: Build APK

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '11' # Specify the JDK version you need

    - name: Install Android SDK
      run: |
        sudo apt-get update
        sudo apt-get install -y wget unzip
        wget https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip
        unzip commandlinetools-linux-8512546_latest.zip -d $HOME/android-sdk
        echo "export ANDROID_HOME=$HOME/android-sdk" >> $GITHUB_ENV
        echo "export PATH=$ANDROID_HOME/cmdline-tools/bin:$PATH" >> $GITHUB_ENV
        sdkmanager --update

    - name: Install Android SDK Build Tools
      run: sdkmanager "build-tools;30.0.3" "platforms;android-30"

    - name: Build APK
      run: |
        cd app/src/main
        javac -d out $(find . -name '*.java')
        jar cvf app-release.jar -C out .
        # Adjust the following command if needed based on your setup
        # Use `aapt` and `zipalign` to create APK if necessary
        # Example:
        # aapt package -f -m -J src -S res -M AndroidManifest.xml -F app-release.apk
        # zipalign -v 4 app-release.apk app-release-aligned.apk
        # apksigner sign --ks my-release-key.jks --out app-release-signed.apk app-release-aligned.apk
        # cp app-release-signed.apk ../app-release.apk
