name: Build APK

on:
  push:
    branches:
      - main  # Change this to your default branch if different
  pull_request:
    branches:
      - main  # Change this to your default branch if different

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '11'  # Use the version required by your project

    - name: Build with Gradle
      uses: gradle/gradle-build-action@v3
      with:
        arguments: assembleRelease  # or assembleDebug depending on your needs

    - name: Archive APK
      uses: actions/upload-artifact@v3
      with:
        name: apk
        path: app/build/outputs/apk/release/app-release.apk  # Adjust the path if necessary
